version: "3"

networks:
  some-network:

services:
  app:
    build: ./build
    container_name: app
    depends_on:
      - cassandra1
      - cassandra2
    networks:
      - some-network
    ports:
      - 8080:80
    privileged: true
    environment:
      JAVA_HOME: /usr/local/java
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/java/bin
    volumes:
      - ./volumes/opt:/opt
      - ./volumes/tmp:/tmp
      - ../build:/opt/java
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    working_dir: /root
    entrypoint: >
      bash -c "
        sh /tmp/container-init.sh &&
        tail -f /dev/null
      "

  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    networks:
      - some-network
    environment:
      CASSANDRA_SEEDS: cassandra1, cassandra2
      CASSANDRA_CLUSTER_NAME: business-discovery-cluster
    volumes:
      - ./volumes/cassandra1/datadir:/var/lib/cassandra
    restart: always

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    networks:
      - some-network
    environment:
      CASSANDRA_SEEDS: cassandra1, cassandra2
      CASSANDRA_CLUSTER_NAME: business-discovery-cluster
    volumes:
      - ./volumes/cassandra2/datadir:/var/lib/cassandra
    restart: always
